/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.Conexion;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
/**
 *
 * @author juans
 */
public class ver_rutas extends javax.swing.JFrame {

    
    Conexion con = new Conexion();
    Connection cn;
    Statement st;//El objeto Statement (sentencia) sirve para procesar una sentencia SQL estática y obtener los resultados producidos por ella.
    ResultSet rs;
    DefaultTableModel model;
    /**
     * Creates new form FrameHospital
     */
    public ver_rutas() {
        initComponents();
        setLocationRelativeTo(this);
        show_route();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_Barrio = new javax.swing.JTextField();
        txt_idRuta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_kilometros = new javax.swing.JTextField();
        ID_hospitals = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_DF = new javax.swing.JTextField();
        ID_hospitals1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_DI = new javax.swing.JTextField();
        ID_hospitals2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_HI = new javax.swing.JTextField();
        txt_HF = new javax.swing.JTextField();
        txt_usuario = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_schedule = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(22, 132, 206));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Barrio");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Id de ruta");

        ID_hospitals.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ID_hospitals.setText("km");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Registro de rutas");

        ID_hospitals1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ID_hospitals1.setText("Dia de finalizacion");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Dia de inicio");

        ID_hospitals2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ID_hospitals2.setText("Hora de finalizacion");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Hora de inicio");

        txt_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ID_hospitals)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_kilometros, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_idRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Barrio, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ID_hospitals2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ID_hospitals1)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_HF, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_DF, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_HI, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txt_DI, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Barrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_idRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ID_hospitals1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_DI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_DF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ID_hospitals)
                        .addComponent(txt_kilometros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_HI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID_hospitals2)
                            .addComponent(txt_HF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37))
        );

        btn_add.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_add.setText("Agregar ruta");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_delete.setText("Eliminar Clinica");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_edit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_edit.setText("editar ruta");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btn_add)
                .addGap(18, 18, 18)
                .addComponent(btn_delete)
                .addGap(18, 18, 18)
                .addComponent(btn_edit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_schedule.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbl_schedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barrio", "Codigo de ruta", "kilometros", "Dia inicial", "Dia final", "Hora inicial", "Hora final"
            }
        ));
        tbl_schedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_scheduleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_schedule);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Historial de clinicas de mascotas");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(195, 195, 195))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_scheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_scheduleMouseClicked
      
        int row = tbl_schedule.getSelectedRow();
        if (row >= 0) {
            String barrio = tbl_schedule.getValueAt(row, 0).toString();
            String idRuta = tbl_schedule.getValueAt(row, 1).toString();
            int km = Integer.parseInt(tbl_schedule.getValueAt(row, 2).toString());
            int DI = Integer.parseInt(tbl_schedule.getValueAt(row, 3).toString());
            int DF = Integer.parseInt(tbl_schedule.getValueAt(row, 4).toString());
            int HI = Integer.parseInt(tbl_schedule.getValueAt(row, 5).toString());
            int HF = Integer.parseInt(tbl_schedule.getValueAt(row, 6).toString());
            
       txt_Barrio.setText(""+barrio);
        txt_idRuta.setText(""+idRuta);
        txt_kilometros.setText(""+km);
        txt_DF.setText(""+DI);
        txt_DI.setText(""+DF);
        txt_HI.setText(""+HI);
        txt_HF.setText(""+HF);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_scheduleMouseClicked

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
       add_route();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        delete_route();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        edit_route();
    }//GEN-LAST:event_btn_editActionPerformed

  void show_route(){
        String query = "SELECT * FROM tb_route";
        try{
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(query);
            Object[] schedule = new Object[7];
            model = (DefaultTableModel)tbl_schedule.getModel();
            while(rs.next()){
                 schedule[0] = rs.getString("barrio");
                 schedule[1] = rs.getString("idRuta");
                 schedule[2] = rs.getInt("km");
                 schedule[3] = rs.getInt("star_date");
                 schedule[4] = rs.getInt("end_date");
                 schedule[5] = rs.getInt("star_hour");
                 schedule[6] = rs.getInt("end_hour");
                model.addRow(schedule);
            }
            tbl_schedule.setModel(model);
        }catch(SQLException e){
            JOptionPane.showConfirmDialog(this, "No se encontraron registros de rutas");
        }
    }


    

    
    void clear_rows_table(){
        for (int i = 0; i < tbl_schedule.getRowCount(); i++) {
            model.removeRow(i);
            i -= 1;
        }
        txt_Barrio.setText("");
        txt_idRuta.setText("");
        txt_kilometros.setText("");
        txt_DF.setText("");
        txt_DI.setText("");
        txt_HI.setText("");
        txt_HF.setText("");
    }



    void delete_route(){
      int row_schedule = tbl_schedule.getSelectedRow();
            if(row_schedule  < 0){
                 JOptionPane.showMessageDialog(this, "Debes de seleccionar un registro de la tabla");
            }else{
      
            String idRuta = txt_idRuta.getText();
            if(row_schedule == -1)
                JOptionPane.showMessageDialog(this, "Debes de seleccionar un registro de la tabla");
                else{
                    String sql = "DELETE FROM `tb_route` WHERE idRuta = "+idRuta;
                    try{
                      
                        cn = con.getConnection();
                        st = cn.createStatement();
                        st.executeUpdate(sql);
                        clear_rows_table();
                        JOptionPane.showMessageDialog(this, "Se ha eliminado el registro");
                        show_route();
                    }catch(SQLException e){
                        JOptionPane.showMessageDialog(this, "No se pudo eliminar la información del registro");
                    }
                }
       }
    }
    

    
    public void showName(String name){
        
        txt_usuario.setText(name);
    }
    void add_route() {
        DateTimeFormatter dtf4 = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm");
        String fecha = dtf4.format(LocalDateTime.now());
  
        String mes = String.valueOf(fecha.charAt(8));
         mes = mes +""+ String.valueOf(fecha.charAt(9));
         
        String hora = String.valueOf(fecha.charAt(11));
         hora = hora +""+ String.valueOf(fecha.charAt(12));
         
         System.out.println(""+mes+ "   "+hora);
         
         int mesN = Integer.parseInt(mes);
         int hotaN = Integer.parseInt(hora);
        
        
        String barrio = txt_Barrio.getText();
        String idRuta = txt_idRuta.getText();
        int km = Integer.parseInt(txt_kilometros.getText()) ;
        int star_date = Integer.parseInt(txt_DI.getText());
        int end_date =  Integer.parseInt(txt_DF.getText());
        int star_hour = Integer.parseInt(txt_HI.getText());
        int end_hour  = Integer.parseInt(txt_HF.getText());
                
        if (barrio.isEmpty() || idRuta.isEmpty() || km<=0 || star_date==0 || end_date==0 || star_hour==0 || end_hour==0 || end_date<star_date || end_hour<star_hour ||  mesN>star_date  ) {
               JOptionPane.showMessageDialog(this, "Faltan campos por diligenciar");
        } else if(/*SearchSameName(hospital) == false*/true){
            String query = "INSERT INTO tb_route(barrio,star_date,end_date,star_hour,end_hour,idRuta,km)VALUES('" + barrio + "','" +star_date + "','" + end_date + "','" +star_hour +"','" + end_hour + "','"+ idRuta + "','" +km +"')";
            try {
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(query);
                
                JOptionPane.showMessageDialog(this, "Se ha creado el registro con éxito");
                clear_rows_table();
                show_route();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "No se pudo crear el registro");
            }
        }else{
             JOptionPane.showMessageDialog(this, "Mismo nombre");
        }
    }

  void edit_route(){
            int rowRoute =  tbl_schedule.getSelectedRow();
            if(rowRoute  < 0){
                 JOptionPane.showMessageDialog(this, "Debes de seleccionar un registro de la tabla");
            }else{
                        DateTimeFormatter dtf4 = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm");
                String fecha = dtf4.format(LocalDateTime.now());

                String mes = String.valueOf(fecha.charAt(8));
                 mes = mes +""+ String.valueOf(fecha.charAt(9));

                String hora = String.valueOf(fecha.charAt(11));
                 hora = hora +""+ String.valueOf(fecha.charAt(12));

                 int mesN = Integer.parseInt(mes);
                 int hotaN = Integer.parseInt(hora);
        
    
                String barrio = txt_Barrio.getText();
                  String idRuta = txt_idRuta.getText();
                  int km = Integer.parseInt(txt_kilometros.getText()) ;
                  int star_date = Integer.parseInt(txt_DI.getText());
                  int end_date =  Integer.parseInt(txt_DF.getText());
                  int star_hour = Integer.parseInt(txt_HI.getText());
                  int end_hour  = Integer.parseInt(txt_HF.getText());
                
                    if (barrio.isEmpty() || idRuta.isEmpty() || km<=0 || star_date==0 || end_date==0 || star_hour==0 || end_hour==0 || end_date>star_date || end_hour<star_hour ||  mesN>star_date  ){
                    JOptionPane.showMessageDialog(this, "Faltan campos por diligenciar");
                }else{
                    String sql = "UPDATE `tb_route` SET `barrio` = '"+barrio+"', `star_date`= '"+star_date +"', `end_date`= '"+end_date +"', `star_hour`= '"+star_hour +"', `end_hour`= '"+end_hour +"', `idRuta`= '"+idRuta+"', `km`= '"+km+"' WHERE `idRuta` = "+idRuta;
                    
                    try{
                        cn = con.getConnection();
                        st = cn.createStatement();
                        st.executeUpdate(sql);
               
                        JOptionPane.showMessageDialog(this, "Se ha actualizado el registro");
                                 clear_rows_table();
                        show_route();
                    }catch(SQLException e){
                        JOptionPane.showMessageDialog(this, "No se pudo actualizar la información del registro  "+e);
                    }
                }
        }
  }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID_hospitals;
    private javax.swing.JLabel ID_hospitals1;
    private javax.swing.JLabel ID_hospitals2;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_schedule;
    private javax.swing.JTextField txt_Barrio;
    private javax.swing.JTextField txt_DF;
    private javax.swing.JTextField txt_DI;
    private javax.swing.JTextField txt_HF;
    private javax.swing.JTextField txt_HI;
    private javax.swing.JTextField txt_idRuta;
    private javax.swing.JTextField txt_kilometros;
    private javax.swing.JLabel txt_usuario;
    // End of variables declaration//GEN-END:variables
}
